####
# ATENTION:
# Replace all occurences of sandbox with your project's name
####

# v2 syntax
version: '2'

# Named volumes
volumes:

  # MySQL Data
  mobly-mysql-data:
    driver: local

  # Redis Data
  mobly-redis-data:
    driver: local

  # Redis Data
  mobly-elasticsearch:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: mobly-mysql
    volumes:
      - mobly-mysql-data:/var/lib/mysql
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mobly
      - MYSQL_DATABASE=mobly
      - MYSQL_USER=mobly
      - MYSQL_PASSWORD=mobly

  # Redis
  cache:
    image: redis:4.0
    container_name: mobly-redis
    command: --appendonly yes
    volumes:
      - mobly-redis-data:/data
    ports:
      - "6380:6379"

  elasticsearch:
    image: elasticsearch:5-alpine
    container_name: elastic-search
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - elasticsearch:tag
    volumes:
      - mobly-elasticsearch

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.2-nginx
    container_name: mobly-app
    volumes:
      - .:/var/www/app
    ports:
      - "7000:8080"
    links:
      - mysql
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.2
    container_name: mobly-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache
      - elasticsearch